source 'https://rubygems.org'

gem 'sinatra', require: 'sinatra/base'
gem 'shotgun'
gem 'pry'
gem 'pry-nav'
gem 'minitest'
gem 'capybara'
gem 'launchy'
gem 'rake'
gem 'sequel'
gem 'sqlite3'
gem 'database_cleaner'
